model = "gpt-5.3-codex"
personality = "pragmatic"
model_reasoning_effort = "high"
web_search = "live"
ask_for_approval = "on-request"

[projects."/Users/kylekthompson/.dotfiles"]
trust_level = "trusted"

[projects."/Users/kylekthompson/src/SomeSoftwareCompany/slumberops"]
trust_level = "trusted"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "/Users/kylekthompson/.bundle",
  "/Users/kylekthompson/.cache",
  "/Users/kylekthompson/.local/share/mise"
]

[tui]
notifications = true
notification_method = "osc9"
